# This file generates the GitHub Actions matrix
# For simple board + shield combinations, where shield compatibility is presumed
# by the existence of shield code in the ZMK tree, you can simply specify:
#
# board: [nice_nano_v2]
# shield: [corne_left, corne_right]
#
# See https://zmk.dev/docs/user-setup#buildinyaml-configuration for more details.

include:
  - board: nice_nano_v2 # Or nice_nano if you have v1
    shield: corne_left # This will build the firmware for the left half
  - board: nice_nano_v2 # Or nice_nano if you have v1
    shield: corne_right # This will build the firmware for the right half
